version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
  - dependency-name: k8s.io/api
    versions:
    - 0.20.3
    - 0.20.4
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.3
    - 0.20.4
  - dependency-name: k8s.io/client-go
    versions:
    - 0.20.3
