env:
- CGO_ENABLED=0
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
  footer: |
    You can verify the signature of the checksums.txt file using [cosign](https://github.com/sigstore/cosign).

    ```
    cosign verify-blob checksums.txt --signature=checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
    ```
signs:
- cmd: cosign
  args: ["sign-blob", "--key=hashivault://cosign", "-output-signature=${signature}", "${artifact}"]
  artifacts: checksum
brews:
- name: rbac-lookup
  tap:
    # The version control system is determined by the token in use
    owner: FairwindsOps
    name: homebrew-tap
  folder: Formula
  description: Reverse Lookup for Kubernetes RBAC
  homepage: https://github.com/FairWindsOps/rbac-lookup
  license: apache-2.0
  test: |
    system "#{bin}/rbac-lookup version"
