# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- name: homebrew-tap
  tap:
    # The version control system is determined by the token in use
    owner: FairwindsOps
    name: homebrew-tap
  folder: Formula
  description: Reverse Lookup for Kubernetes RBAC
  homepage: https://github.com/FairWindsOps/rbac-lookup
  license: apache-2.0
  test: |
    system "#{bin}/rbac-lookup version"
