version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@9.4.0

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.94.0/goreleaser_amd64.deb
        echo "8dbad6683d6fc9367e637e6eed8e01a0d63c9660  goreleaser.deb" | sha1sum -c
        sudo dpkg -i goreleaser.deb
        rm goreleaser.deb

jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup

    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - *install_goreleaser
      - run: goreleaser

workflows:
  version: 2
  test-and-release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - rok8s-scripts/kubernetes_e2e_tests:
          pre_script: e2e/pre.sh
          script: e2e/test.sh
          requires:
            - test
            - build
          filters:
            branches:
              only: mh/e2e-testing
            tags:
              ignore: /v.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
