version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11
  oss-docs: fairwinds/oss-docs@0

executors:
  golang-exec:
    docker:
      - image: cimg/go:1.18

references:
  e2e_config: &e2e_config
    command_runner_image: quay.io/reactiveops/ci-images:v11-stretch
    executor: golang-exec
    pre_script: e2e/pre.sh
    store-test-results: /tmp/test-results
    script: e2e/test.sh
    requires:
      - test
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/
  install_vault_alpine: &install_vault_alpine
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.9.3/vault_1.9.3_linux_amd64.zip
        unzip vault_1.9.3_linux_amd64.zip
        mv vault /usr/bin/vault
jobs:
  test:
    working_directory: /home/circleci/go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: cimg/go:1.18
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  snapshot:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: goreleaser/goreleaser:v1.3.0
    steps:
      - checkout
      - setup_remote_docker
      - run: goreleaser --snapshot --skip-sign
      - store_artifacts:
          path: dist
          destination: snapshot
  release:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: goreleaser/goreleaser:v1.3.0
    steps:
      - checkout
      - setup_remote_docker
      - *install_vault_alpine
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - rok8s/get_vault_env:
          vault_path: repo/rbac-lookup/env
      - run: go mod download && go mod verify
      - run: goreleaser
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.19"
          kind_node_image: "kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729"
          <<: *e2e_config
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.20"
          kind_node_image: "kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9"
          <<: *e2e_config
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.21"
          kind_node_image: "kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6"
          <<: *e2e_config
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.22"
          kind_node_image: "kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047"
          <<: *e2e_config
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - oss-docs/publish-docs:
          repository: rbac-manager
          filters:
            branches:
              #ignore: /.*/
              only: sudermanjr/oss-docs
            tags:
              only: /^.*/
