version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@11

executors:
  golang-exec:
    docker:
      - image: circleci/golang:1.13-stretch

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.155.0/goreleaser_amd64.deb
        echo "a69c2c0a924d808df408f70f49c68998eca172ec  goreleaser.deb" | sha1sum -c
        sudo dpkg -i goreleaser.deb
        rm goreleaser.deb
  e2e_config: &e2e_config
    command_runner_image: quay.io/reactiveops/ci-images:v11-stretch
    executor: golang-exec
    pre_script: e2e/pre.sh
    store-test-results: /tmp/test-results
    kind_version: 0.9.0
    script: e2e/test.sh
    requires:
      - test
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/

jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup

    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - *install_goreleaser
      - run: goreleaser
  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: Build Docs Site
          command: |
            set -e
            cd ./docs
            npm install
            npm run check-links
            npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://rbac-lookup.docs.fairwinds.com --delete

workflows:
  version: 2
  test-and-release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - rok8s-scripts/kubernetes_e2e_tests:
          name: e2e test kube 1.16
          kind_node_image: "kindest/node:v1.16.15@sha256:a89c771f7de234e6547d43695c7ab047809ffc71a0c3b65aa54eda051c45ed20"
          <<: *e2e_config
      - rok8s-scripts/kubernetes_e2e_tests:
          name: e2e test kube 1.17
          kind_node_image: "kindest/node:v1.17.11@sha256:5240a7a2c34bf241afb54ac05669f8a46661912eab05705d660971eeb12f6555"
          <<: *e2e_config
      - rok8s-scripts/kubernetes_e2e_tests:
          name: e2e test kube 1.18
          kind_node_image: "kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb"
          <<: *e2e_config
      - rok8s-scripts/kubernetes_e2e_tests:
          name: e2e test kube 1.19
          kind_node_image: "kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600"
          <<: *e2e_config
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_docs:
          filters:
            branches:
              only: sudermanjr/docs-site
            tags:
              only: /.*/
