version: 2

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.94.0/goreleaser_amd64.deb
        echo "8dbad6683d6fc9367e637e6eed8e01a0d63c9660  goreleaser.deb" | sha1sum -c
        sudo dpkg -i goreleaser.deb

jobs:
  build:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/reactiveops/rbac-lookup

    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: go mod download && go mod verify
      - *install_goreleaser
      - run: goreleaser

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
