version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@12
  oss-docs: fairwinds/oss-docs@0

executors:
  golang-exec:
    docker:
      - image: cimg/go:1.20

references:
  e2e_configuration: &e2e_configuration
    command_runner_image: quay.io/reactiveops/ci-images:v12-buster
    executor: golang-exec
    pre_script: e2e/pre.sh
    store-test-results: /tmp/test-results
    script: e2e/test.sh
    requires:
      - test
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/
  install_vault_alpine: &install_vault_alpine
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.13.2/vault_1.13.2_linux_amd64.zip
        sha256sum vault_1.13.2_linux_amd64.zip | grep f7930279de8381de7c532164b4a4408895d9606c0d24e2e9d2f9acb5dfe99b3c
        unzip vault_1.13.2_linux_amd64.zip
        mv vault /usr/bin/vault
jobs:
  test:
    working_directory: /home/circleci/go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: cimg/go:1.20
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  snapshot:
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    resource_class: large
    docker:
      - image: goreleaser/goreleaser:v1.18.2
    steps:
      - checkout
      - setup_remote_docker
      - run: goreleaser --snapshot --skip-sign
      - store_artifacts:
          path: dist
          destination: snapshot
  release:
    resource_class: large
    working_directory: /go/src/github.com/fairwindsops/rbac-lookup
    docker:
      - image: goreleaser/goreleaser:v1.18.2
    steps:
      - checkout
      - setup_remote_docker
      - *install_vault_alpine
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - rok8s/get_vault_env:
          vault_path: repo/rbac-lookup/env
      - run: go mod download && go mod verify
      - run: goreleaser
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.23"
          kind_node_image: "kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61"
          <<: *e2e_configuration
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.24"
          kind_node_image: "kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315"
          <<: *e2e_configuration
      - rok8s/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.25"
          kind_node_image: "kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
          <<: *e2e_configuration
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - oss-docs/publish-docs:
          repository: rbac-lookup
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
